version: '3.8'

services:
  # قاعدة بيانات MySQL
  mysql:
    image: mysql:8.0
    container_name: techverse_mysql
    environment:
      MYSQL_ROOT_PASSWORD: techverse_root_password
      MYSQL_DATABASE: techverse_db
      MYSQL_USER: techverse_user
      MYSQL_PASSWORD: techverse_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - techverse_network

  # قاعدة بيانات PostgreSQL
  postgres:
    image: postgres:15
    container_name: techverse_postgres
    environment:
      POSTGRES_DB: techverse_analytics
      POSTGRES_USER: techverse_user
      POSTGRES_PASSWORD: techverse_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - techverse_network

  # قاعدة بيانات MongoDB
  mongodb:
    image: mongo:6.0
    container_name: techverse_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: techverse_password
      MONGO_INITDB_DATABASE: techverse_nosql
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - techverse_network

  # Redis للذاكرة المؤقتة
  redis:
    image: redis:7.2-alpine
    container_name: techverse_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - techverse_network

  # Backend API
  backend:
    build: ./backend
    container_name: techverse_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://techverse_user:techverse_password@mysql:3306/techverse_db
      - POSTGRES_URL=postgresql://techverse_user:techverse_password@postgres:5432/techverse_analytics
      - MONGODB_URL=mongodb://admin:techverse_password@mongodb:27017/techverse_nosql
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET_KEY=your_super_secret_jwt_key_here
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173
    depends_on:
      - mysql
      - postgres
      - mongodb
      - redis
    volumes:
      - ./backend/logs:/app/logs
    networks:
      - techverse_network

  # Frontend React
  frontend:
    build: ./frontend
    container_name: techverse_frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_WS_URL=ws://localhost:8000
    depends_on:
      - backend
    networks:
      - techverse_network

  # Nginx للـ Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: techverse_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    networks:
      - techverse_network

volumes:
  mysql_data:
  postgres_data:
  mongodb_data:
  redis_data:

networks:
  techverse_network:
    driver: bridge